import CompPoly.Data.Array.Lemmas
import CompPoly.Data.Fin.BigOperators
import CompPoly.Data.List.Lemmas
import CompPoly.Data.Nat.Bitwise
import CompPoly.Data.Vector.Basic
import CompPoly.Multilinear.Basic
import CompPoly.Multilinear.Equiv
import CompPoly.Multivariate.CMvMonomial
import CompPoly.Multivariate.CMvPolynomial
import CompPoly.Multivariate.CMvPolynomialEvalLemmas
import CompPoly.Multivariate.Lawful
import CompPoly.Multivariate.MvPolyEquiv
import CompPoly.Multivariate.Unlawful
import CompPoly.Multivariate.Wheels
import CompPoly.Univariate.Raw
import CompPoly.Univariate.Basic
import CompPoly.Univariate.Quotient
import CompPoly.Univariate.ToPoly
import CompPoly.Univariate.Lagrange
